-- Generated import migration from data/seed_csv

create extension if not exists "pgcrypto";

create temporary table staging_employees (
  email text,
  full_name text,
  role user_role,
  department text,
  job_title text,
  years_of_experience int
) on commit drop;

insert into staging_employees (email, full_name, role, department, job_title, years_of_experience) values
  ('employee001@company.com','Aisha Iyer','employee','Data','Senior Software Engineer',13),
  ('employee002@company.com','Akshay Reddy','employee','IT','Data Analyst',5),
  ('employee003@company.com','Ananya Patel','employee','HR','Data Scientist',1),
  ('employee004@company.com','Arjun Singh','employee','Design','BI Analyst',9),
  ('employee005@company.com','Bhavya Nair','employee','Product','Backend Developer',14),
  ('employee006@company.com','Charan Kapoor','employee','Finance','Frontend Developer',4),
  ('employee007@company.com','Diya Mehta','employee','Security','Full Stack Developer',13),
  ('employee008@company.com','Eshan Das','employee','Engineering','Cloud Engineer',13),
  ('employee009@company.com','Farah Verma','employee','Data','DevOps Engineer',1),
  ('employee010@company.com','Gauri Rao','employee','IT','QA Engineer',12),
  ('employee011@company.com','Harish Menon','employee','HR','Security Analyst',1),
  ('employee012@company.com','Ishita Bose','employee','Design','HR Manager',14),
  ('employee013@company.com','Jai Joshi','employee','Product','Talent Manager',5),
  ('employee014@company.com','Kiran Mishra','employee','Finance','Recruitment Specialist',10),
  ('employee015@company.com','Lakshya Khan','employee','Security','UI UX Designer',3),
  ('employee016@company.com','Meera Gupta','employee','Engineering','Product Designer',3),
  ('employee017@company.com','Nikhil Pillai','employee','Data','Product Manager',9),
  ('employee018@company.com','Oviya Chopra','employee','IT','Engineering Manager',12),
  ('employee019@company.com','Pranav Banerjee','employee','HR','Team Lead',5),
  ('employee020@company.com','Rhea Sharma','employee','Design','Software Engineer',4),
  ('employee021@company.com','Saanvi Iyer','employee','Product','Senior Software Engineer',3),
  ('employee022@company.com','Tarun Reddy','employee','Finance','Data Analyst',13),
  ('employee023@company.com','Uma Patel','employee','Security','Data Scientist',7),
  ('employee024@company.com','Varun Singh','employee','Engineering','BI Analyst',11),
  ('employee025@company.com','Yash Nair','employee','Data','Backend Developer',7),
  ('employee026@company.com','Zara Kapoor','employee','IT','Frontend Developer',11),
  ('employee027@company.com','Aditya Mehta','employee','HR','Full Stack Developer',7),
  ('employee028@company.com','Bina Das','employee','Design','Cloud Engineer',14),
  ('employee029@company.com','Chetan Verma','employee','Product','DevOps Engineer',12),
  ('employee030@company.com','Devika Rao','employee','Finance','QA Engineer',14),
  ('employee031@company.com','Ekta Menon','employee','Security','Security Analyst',10),
  ('employee032@company.com','Faisal Bose','employee','Engineering','HR Manager',7),
  ('employee033@company.com','Geeta Joshi','employee','Data','Talent Manager',13),
  ('employee034@company.com','Hema Mishra','employee','IT','Recruitment Specialist',4),
  ('employee035@company.com','Inder Khan','employee','HR','UI UX Designer',7),
  ('employee036@company.com','Jhanvi Gupta','employee','Design','Product Designer',7),
  ('employee037@company.com','Kabir Pillai','employee','Product','Product Manager',6),
  ('employee038@company.com','Lavanya Chopra','employee','Finance','Engineering Manager',11),
  ('employee039@company.com','Manav Banerjee','employee','Security','Team Lead',12),
  ('employee040@company.com','Neha Sharma','employee','Engineering','Software Engineer',14),
  ('employee041@company.com','Omkar Iyer','employee','Data','Senior Software Engineer',3),
  ('employee042@company.com','Pooja Reddy','employee','IT','Data Analyst',8),
  ('employee043@company.com','Qadir Patel','employee','HR','Data Scientist',11),
  ('employee044@company.com','Ritika Singh','employee','Design','BI Analyst',1),
  ('employee045@company.com','Siddharth Nair','employee','Product','Backend Developer',1),
  ('employee046@company.com','Tanvi Kapoor','employee','Finance','Frontend Developer',9),
  ('employee047@company.com','Uday Mehta','employee','Security','Full Stack Developer',4),
  ('employee048@company.com','Vidya Das','employee','Engineering','Cloud Engineer',10),
  ('employee049@company.com','Wasim Verma','employee','Data','DevOps Engineer',2),
  ('employee050@company.com','Xena Rao','employee','IT','QA Engineer',9),
  ('employee051@company.com','Yamini Menon','employee','HR','Security Analyst',15),
  ('employee052@company.com','Zubin Bose','employee','Design','HR Manager',11),
  ('employee053@company.com','Aarav Joshi','employee','Product','Talent Manager',2),
  ('employee054@company.com','Aisha Mishra','employee','Finance','Recruitment Specialist',14),
  ('employee055@company.com','Akshay Khan','employee','Security','UI UX Designer',15),
  ('employee056@company.com','Ananya Gupta','employee','Engineering','Product Designer',4),
  ('employee057@company.com','Arjun Pillai','employee','Data','Product Manager',10),
  ('employee058@company.com','Bhavya Chopra','employee','IT','Engineering Manager',11),
  ('employee059@company.com','Charan Banerjee','employee','HR','Team Lead',15),
  ('employee060@company.com','Diya Sharma','employee','Design','Software Engineer',1),
  ('employee061@company.com','Eshan Iyer','employee','Product','Senior Software Engineer',9),
  ('employee062@company.com','Farah Reddy','employee','Finance','Data Analyst',14),
  ('employee063@company.com','Gauri Patel','employee','Security','Data Scientist',13),
  ('employee064@company.com','Harish Singh','employee','Engineering','BI Analyst',7),
  ('employee065@company.com','Ishita Nair','employee','Data','Backend Developer',10),
  ('employee066@company.com','Jai Kapoor','employee','IT','Frontend Developer',12),
  ('employee067@company.com','Kiran Mehta','employee','HR','Full Stack Developer',15),
  ('employee068@company.com','Lakshya Das','employee','Design','Cloud Engineer',7),
  ('employee069@company.com','Meera Verma','employee','Product','DevOps Engineer',13),
  ('employee070@company.com','Nikhil Rao','employee','Finance','QA Engineer',2),
  ('employee071@company.com','Oviya Menon','employee','Security','Security Analyst',10),
  ('employee072@company.com','Pranav Bose','employee','Engineering','HR Manager',14),
  ('employee073@company.com','Rhea Joshi','employee','Data','Talent Manager',14),
  ('employee074@company.com','Saanvi Mishra','employee','IT','Recruitment Specialist',2),
  ('employee075@company.com','Tarun Khan','employee','HR','UI UX Designer',7),
  ('employee076@company.com','Uma Gupta','employee','Design','Product Designer',5),
  ('employee077@company.com','Varun Pillai','employee','Product','Product Manager',13),
  ('employee078@company.com','Yash Chopra','employee','Finance','Engineering Manager',11),
  ('employee079@company.com','Zara Banerjee','employee','Security','Team Lead',7),
  ('employee080@company.com','Aditya Sharma','employee','Engineering','Software Engineer',7),
  ('employee081@company.com','Bina Iyer','employee','Data','Senior Software Engineer',4),
  ('employee082@company.com','Chetan Reddy','employee','IT','Data Analyst',8),
  ('employee083@company.com','Devika Patel','employee','HR','Data Scientist',14),
  ('employee084@company.com','Ekta Singh','employee','Design','BI Analyst',1),
  ('employee085@company.com','Faisal Nair','team_lead','Product','Backend Developer',13),
  ('employee086@company.com','Geeta Kapoor','team_lead','Finance','Frontend Developer',8),
  ('employee087@company.com','Hema Mehta','team_lead','Security','Full Stack Developer',4),
  ('employee088@company.com','Inder Das','team_lead','Engineering','Cloud Engineer',9),
  ('employee089@company.com','Jhanvi Verma','team_lead','Data','DevOps Engineer',11),
  ('employee090@company.com','Kabir Rao','team_lead','IT','QA Engineer',9),
  ('employee091@company.com','Lavanya Menon','team_lead','HR','Security Analyst',15),
  ('employee092@company.com','Manav Bose','team_lead','Design','HR Manager',13),
  ('employee093@company.com','Neha Joshi','team_lead','Product','Talent Manager',11),
  ('employee094@company.com','Omkar Mishra','team_lead','Finance','Recruitment Specialist',6),
  ('employee095@company.com','Pooja Khan','hr_manager','Security','UI UX Designer',9),
  ('employee096@company.com','Qadir Gupta','hr_manager','Engineering','Product Designer',5),
  ('employee097@company.com','Ritika Pillai','hr_manager','Data','Product Manager',2),
  ('employee098@company.com','Siddharth Chopra','hr_manager','IT','Engineering Manager',10),
  ('employee099@company.com','Tanvi Banerjee','hr_manager','HR','Team Lead',15),
  ('employee100@company.com','Uday Sharma','org_admin','Design','Software Engineer',14);

-- Seed auth users for all staging employees (idempotent)
insert into auth.users (
  id, aud, role, email, encrypted_password, email_confirmed_at, invited_at, confirmation_sent_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at
)
select
  gen_random_uuid(),
  'authenticated',
  'authenticated',
  se.email,
  extensions.crypt('TempPass#2026', extensions.gen_salt('bf')),
  now(),
  now(),
  now(),
  jsonb_build_object('provider', 'email', 'providers', array['email']),
  jsonb_build_object('full_name', se.full_name, 'role', se.role::text),
  now(),
  now()
from staging_employees se
where not exists (select 1 from auth.users au where lower(au.email) = lower(se.email));

-- Ensure auth identities exist
insert into auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at)
select
  gen_random_uuid(),
  au.id,
  au.email,
  jsonb_build_object('sub', au.id::text, 'email', au.email),
  'email',
  now(),
  now()
from auth.users au
join staging_employees se on lower(se.email) = lower(au.email)
where not exists (select 1 from auth.identities ai where ai.user_id = au.id and ai.provider = 'email');

-- Upsert profiles from staging
insert into public.profiles (id, email, full_name, role, department, job_title, years_of_experience)
select au.id, se.email, se.full_name, se.role, se.department, se.job_title, se.years_of_experience
from staging_employees se
join auth.users au on lower(au.email) = lower(se.email)
on conflict (id) do update set
  email = excluded.email,
  full_name = excluded.full_name,
  role = excluded.role,
  department = excluded.department,
  job_title = excluded.job_title,
  years_of_experience = excluded.years_of_experience,
  updated_at = now();

create temporary table staging_skills (name text, category skill_category, market_demand_score int) on commit drop;
insert into staging_skills (name, category, market_demand_score) values
  ('Python','technical',96),
  ('SQL','technical',93),
  ('Java','technical',88),
  ('C#','technical',82),
  ('Go','technical',85),
  ('JavaScript','technical',92),
  ('TypeScript','technical',91),
  ('React','technical',94),
  ('Angular','technical',79),
  ('Vue','technical',76),
  ('Node.js','technical',90),
  ('Spring Boot','technical',84),
  ('Django','technical',80),
  ('Flask','technical',78),
  ('FastAPI','technical',83),
  ('Machine Learning','technical',97),
  ('Deep Learning','technical',95),
  ('Data Analysis','technical',89),
  ('Tableau','technical',81),
  ('Power BI','technical',84),
  ('Excel','technical',74),
  ('AWS','technical',98),
  ('Azure','technical',90),
  ('GCP','technical',88),
  ('Docker','technical',92),
  ('Kubernetes','technical',91),
  ('Terraform','technical',86),
  ('Linux','technical',87),
  ('Git','technical',85),
  ('CI CD','technical',84),
  ('Cybersecurity','technical',89),
  ('Testing Automation','technical',83),
  ('Prompt Engineering','technical',90),
  ('System Design','technical',93),
  ('REST APIs','technical',91),
  ('GraphQL','technical',80),
  ('Communication','soft',85),
  ('Leadership','soft',87),
  ('Problem Solving','soft',90),
  ('Teamwork','soft',84),
  ('Negotiation','soft',76),
  ('Time Management','soft',79),
  ('Adaptability','soft',82),
  ('Stakeholder Management','soft',80),
  ('Agile Methodology','domain',88),
  ('Project Management','domain',89),
  ('Product Strategy','domain',81),
  ('UI UX Design','domain',83);

insert into public.skills (name, category, market_demand_score)
select name, category, market_demand_score from staging_skills
on conflict (name) do update set
  category = excluded.category,
  market_demand_score = excluded.market_demand_score;

create temporary table staging_employee_skills (employee_email text, skill_name text, proficiency proficiency_level, self_rated boolean) on commit drop;
insert into staging_employee_skills (employee_email, skill_name, proficiency, self_rated) values
  ('employee001@company.com','Adaptability','intermediate',true),
  ('employee001@company.com','Azure','advanced',true),
  ('employee001@company.com','CI CD','intermediate',true),
  ('employee001@company.com','Data Analysis','expert',true),
  ('employee001@company.com','Go','expert',true),
  ('employee001@company.com','Java','expert',true),
  ('employee001@company.com','Linux','advanced',true),
  ('employee001@company.com','Power BI','advanced',true),
  ('employee001@company.com','Spring Boot','intermediate',true),
  ('employee002@company.com','Agile Methodology','beginner',true),
  ('employee002@company.com','C#','intermediate',true),
  ('employee002@company.com','Django','advanced',true),
  ('employee002@company.com','Machine Learning','advanced',true),
  ('employee002@company.com','Node.js','beginner',true),
  ('employee002@company.com','Python','expert',true),
  ('employee002@company.com','REST APIs','beginner',true),
  ('employee002@company.com','System Design','beginner',true),
  ('employee002@company.com','Time Management','advanced',false),
  ('employee002@company.com','UI UX Design','intermediate',true),
  ('employee003@company.com','Agile Methodology','intermediate',true),
  ('employee003@company.com','Azure','intermediate',false),
  ('employee003@company.com','Cybersecurity','advanced',false),
  ('employee003@company.com','Data Analysis','advanced',true),
  ('employee003@company.com','Django','beginner',false),
  ('employee003@company.com','Excel','intermediate',true),
  ('employee003@company.com','Kubernetes','beginner',true),
  ('employee003@company.com','Negotiation','expert',true),
  ('employee003@company.com','Time Management','beginner',true),
  ('employee003@company.com','UI UX Design','advanced',true),
  ('employee004@company.com','Agile Methodology','beginner',true),
  ('employee004@company.com','AWS','expert',false),
  ('employee004@company.com','Cybersecurity','expert',true),
  ('employee004@company.com','Django','intermediate',true),
  ('employee004@company.com','Kubernetes','advanced',true),
  ('employee004@company.com','Prompt Engineering','advanced',false),
  ('employee004@company.com','React','beginner',true),
  ('employee004@company.com','UI UX Design','intermediate',true),
  ('employee005@company.com','C#','beginner',true),
  ('employee005@company.com','Kubernetes','advanced',true),
  ('employee005@company.com','Linux','expert',true),
  ('employee005@company.com','Negotiation','advanced',true),
  ('employee005@company.com','Node.js','expert',true),
  ('employee005@company.com','React','advanced',true),
  ('employee005@company.com','Spring Boot','advanced',false),
  ('employee005@company.com','Terraform','advanced',true),
  ('employee006@company.com','Flask','advanced',true),
  ('employee006@company.com','GCP','advanced',true),
  ('employee006@company.com','Go','advanced',false),
  ('employee006@company.com','Leadership','intermediate',true),
  ('employee006@company.com','Negotiation','intermediate',true),
  ('employee006@company.com','Node.js','advanced',true),
  ('employee006@company.com','Product Strategy','advanced',false),
  ('employee006@company.com','UI UX Design','intermediate',false),
  ('employee006@company.com','Vue','expert',true),
  ('employee007@company.com','CI CD','intermediate',false),
  ('employee007@company.com','Cybersecurity','intermediate',true),
  ('employee007@company.com','Data Analysis','intermediate',false),
  ('employee007@company.com','Deep Learning','expert',true),
  ('employee007@company.com','GCP','expert',false),
  ('employee007@company.com','Problem Solving','advanced',true),
  ('employee007@company.com','React','beginner',true),
  ('employee007@company.com','Teamwork','intermediate',false),
  ('employee007@company.com','Time Management','expert',true),
  ('employee008@company.com','Agile Methodology','expert',true),
  ('employee008@company.com','C#','advanced',false),
  ('employee008@company.com','Communication','advanced',true),
  ('employee008@company.com','Node.js','advanced',true),
  ('employee008@company.com','Problem Solving','advanced',true),
  ('employee008@company.com','Time Management','intermediate',true),
  ('employee008@company.com','UI UX Design','intermediate',false),
  ('employee009@company.com','Adaptability','beginner',true),
  ('employee009@company.com','CI CD','intermediate',true),
  ('employee009@company.com','Communication','beginner',false),
  ('employee009@company.com','Docker','intermediate',true),
  ('employee009@company.com','FastAPI','intermediate',true),
  ('employee009@company.com','Problem Solving','intermediate',false),
  ('employee010@company.com','Angular','beginner',true),
  ('employee010@company.com','C#','advanced',true),
  ('employee010@company.com','FastAPI','expert',true),
  ('employee010@company.com','Java','advanced',false),
  ('employee010@company.com','Node.js','beginner',false),
  ('employee010@company.com','SQL','intermediate',true),
  ('employee010@company.com','Tableau','beginner',true),
  ('employee010@company.com','UI UX Design','expert',false),
  ('employee011@company.com','Angular','beginner',true),
  ('employee011@company.com','Excel','beginner',true),
  ('employee011@company.com','Flask','beginner',true),
  ('employee011@company.com','Git','beginner',true),
  ('employee011@company.com','Java','beginner',true),
  ('employee011@company.com','Linux','beginner',true),
  ('employee011@company.com','Node.js','advanced',false),
  ('employee011@company.com','SQL','intermediate',true),
  ('employee012@company.com','Django','beginner',false),
  ('employee012@company.com','FastAPI','expert',false),
  ('employee012@company.com','Leadership','beginner',true),
  ('employee012@company.com','Negotiation','advanced',false),
  ('employee012@company.com','Problem Solving','beginner',true),
  ('employee012@company.com','Product Strategy','intermediate',true),
  ('employee012@company.com','Spring Boot','beginner',true),
  ('employee012@company.com','Tableau','beginner',false),
  ('employee012@company.com','Terraform','expert',false),
  ('employee013@company.com','Communication','advanced',false),
  ('employee013@company.com','Cybersecurity','beginner',false),
  ('employee013@company.com','Data Analysis','beginner',true),
  ('employee013@company.com','Docker','expert',true),
  ('employee013@company.com','Excel','advanced',true),
  ('employee013@company.com','Flask','advanced',true),
  ('employee013@company.com','Linux','intermediate',true),
  ('employee013@company.com','Machine Learning','beginner',true),
  ('employee013@company.com','Stakeholder Management','advanced',true),
  ('employee014@company.com','Docker','expert',true),
  ('employee014@company.com','Flask','expert',false),
  ('employee014@company.com','Git','beginner',true),
  ('employee014@company.com','Problem Solving','intermediate',true),
  ('employee014@company.com','Prompt Engineering','advanced',true),
  ('employee014@company.com','Python','expert',true),
  ('employee014@company.com','Time Management','intermediate',true),
  ('employee015@company.com','Angular','intermediate',true),
  ('employee015@company.com','Data Analysis','beginner',true),
  ('employee015@company.com','Docker','advanced',true),
  ('employee015@company.com','Git','beginner',false),
  ('employee015@company.com','Java','beginner',true),
  ('employee015@company.com','JavaScript','beginner',true),
  ('employee015@company.com','Power BI','expert',true),
  ('employee015@company.com','Problem Solving','intermediate',true),
  ('employee015@company.com','Project Management','beginner',true),
  ('employee016@company.com','Azure','intermediate',true),
  ('employee016@company.com','Leadership','beginner',false),
  ('employee016@company.com','Node.js','expert',true),
  ('employee016@company.com','Problem Solving','intermediate',false),
  ('employee016@company.com','Python','beginner',false),
  ('employee016@company.com','React','beginner',true),
  ('employee016@company.com','SQL','intermediate',false),
  ('employee016@company.com','System Design','expert',false),
  ('employee016@company.com','Teamwork','expert',true),
  ('employee016@company.com','TypeScript','advanced',true),
  ('employee017@company.com','CI CD','advanced',true),
  ('employee017@company.com','Communication','beginner',false),
  ('employee017@company.com','Deep Learning','intermediate',true),
  ('employee017@company.com','Flask','beginner',true),
  ('employee017@company.com','Linux','intermediate',true),
  ('employee017@company.com','Machine Learning','beginner',true),
  ('employee017@company.com','Spring Boot','expert',true),
  ('employee017@company.com','System Design','beginner',true),
  ('employee017@company.com','Testing Automation','expert',true),
  ('employee018@company.com','Angular','intermediate',false),
  ('employee018@company.com','C#','intermediate',false),
  ('employee018@company.com','Cybersecurity','beginner',false),
  ('employee018@company.com','Java','advanced',true),
  ('employee018@company.com','System Design','expert',true),
  ('employee018@company.com','Teamwork','expert',false),
  ('employee018@company.com','UI UX Design','beginner',false),
  ('employee019@company.com','Agile Methodology','expert',false),
  ('employee019@company.com','Communication','expert',true),
  ('employee019@company.com','Java','intermediate',false),
  ('employee019@company.com','JavaScript','intermediate',true),
  ('employee019@company.com','Kubernetes','advanced',false),
  ('employee019@company.com','Stakeholder Management','expert',true),
  ('employee019@company.com','Tableau','advanced',true),
  ('employee019@company.com','Time Management','intermediate',false),
  ('employee020@company.com','Azure','intermediate',false),
  ('employee020@company.com','Communication','advanced',false),
  ('employee020@company.com','GCP','advanced',true),
  ('employee020@company.com','Go','beginner',true),
  ('employee020@company.com','Java','beginner',true),
  ('employee020@company.com','Kubernetes','expert',false),
  ('employee020@company.com','Leadership','beginner',true),
  ('employee020@company.com','Terraform','intermediate',true),
  ('employee020@company.com','Vue','intermediate',true),
  ('employee021@company.com','Angular','advanced',false),
  ('employee021@company.com','AWS','expert',true),
  ('employee021@company.com','Communication','expert',false),
  ('employee021@company.com','Excel','beginner',true),
  ('employee021@company.com','GraphQL','expert',false),
  ('employee021@company.com','Linux','advanced',true),
  ('employee021@company.com','Machine Learning','expert',true),
  ('employee021@company.com','Tableau','intermediate',true),
  ('employee022@company.com','Adaptability','intermediate',true),
  ('employee022@company.com','AWS','advanced',true),
  ('employee022@company.com','Deep Learning','expert',true),
  ('employee022@company.com','Django','advanced',false),
  ('employee022@company.com','GCP','advanced',true),
  ('employee022@company.com','Git','advanced',false),
  ('employee022@company.com','Kubernetes','intermediate',true),
  ('employee022@company.com','Product Strategy','expert',false),
  ('employee022@company.com','REST APIs','advanced',true),
  ('employee022@company.com','TypeScript','beginner',false),
  ('employee023@company.com','C#','expert',true),
  ('employee023@company.com','Django','beginner',true),
  ('employee023@company.com','FastAPI','expert',false),
  ('employee023@company.com','Kubernetes','advanced',true),
  ('employee023@company.com','Spring Boot','intermediate',true),
  ('employee023@company.com','System Design','beginner',false),
  ('employee023@company.com','Time Management','beginner',true),
  ('employee024@company.com','Angular','beginner',true),
  ('employee024@company.com','Go','beginner',true),
  ('employee024@company.com','GraphQL','beginner',true),
  ('employee024@company.com','Java','intermediate',false),
  ('employee024@company.com','Problem Solving','intermediate',true),
  ('employee024@company.com','Project Management','advanced',true),
  ('employee024@company.com','Prompt Engineering','advanced',true),
  ('employee024@company.com','Teamwork','beginner',false),
  ('employee024@company.com','Testing Automation','beginner',false),
  ('employee025@company.com','Angular','advanced',true),
  ('employee025@company.com','Data Analysis','expert',true),
  ('employee025@company.com','Deep Learning','intermediate',true),
  ('employee025@company.com','FastAPI','advanced',true),
  ('employee025@company.com','Flask','beginner',true),
  ('employee025@company.com','REST APIs','advanced',true),
  ('employee025@company.com','Terraform','beginner',false),
  ('employee025@company.com','TypeScript','beginner',true),
  ('employee026@company.com','Angular','beginner',true),
  ('employee026@company.com','CI CD','beginner',true),
  ('employee026@company.com','Communication','beginner',false),
  ('employee026@company.com','Django','advanced',true),
  ('employee026@company.com','Leadership','advanced',false),
  ('employee026@company.com','Negotiation','expert',true),
  ('employee026@company.com','Product Strategy','advanced',true),
  ('employee026@company.com','Project Management','expert',true),
  ('employee026@company.com','Testing Automation','expert',true),
  ('employee026@company.com','Vue','expert',true),
  ('employee027@company.com','Adaptability','expert',true),
  ('employee027@company.com','Azure','advanced',true),
  ('employee027@company.com','CI CD','beginner',true),
  ('employee027@company.com','Docker','beginner',true),
  ('employee027@company.com','Negotiation','advanced',true),
  ('employee027@company.com','Problem Solving','expert',true),
  ('employee027@company.com','Stakeholder Management','advanced',true),
  ('employee028@company.com','Azure','beginner',true),
  ('employee028@company.com','Java','intermediate',true),
  ('employee028@company.com','Power BI','advanced',true),
  ('employee028@company.com','Python','advanced',false),
  ('employee028@company.com','React','advanced',false),
  ('employee028@company.com','SQL','expert',true),
  ('employee029@company.com','Adaptability','intermediate',false),
  ('employee029@company.com','Deep Learning','beginner',true),
  ('employee029@company.com','Docker','intermediate',true),
  ('employee029@company.com','Project Management','expert',false),
  ('employee029@company.com','Time Management','beginner',false),
  ('employee029@company.com','TypeScript','beginner',true),
  ('employee030@company.com','Agile Methodology','advanced',false),
  ('employee030@company.com','Communication','beginner',false),
  ('employee030@company.com','Deep Learning','expert',true),
  ('employee030@company.com','Excel','beginner',true),
  ('employee030@company.com','Linux','expert',false),
  ('employee030@company.com','Node.js','expert',true),
  ('employee030@company.com','Power BI','intermediate',true),
  ('employee030@company.com','Spring Boot','advanced',true),
  ('employee030@company.com','Stakeholder Management','intermediate',true),
  ('employee030@company.com','UI UX Design','advanced',true),
  ('employee031@company.com','Azure','intermediate',true),
  ('employee031@company.com','Cybersecurity','beginner',true),
  ('employee031@company.com','Excel','advanced',true),
  ('employee031@company.com','JavaScript','advanced',true),
  ('employee031@company.com','Linux','expert',true),
  ('employee031@company.com','Product Strategy','advanced',true),
  ('employee031@company.com','Project Management','expert',false),
  ('employee031@company.com','Python','advanced',true),
  ('employee031@company.com','Stakeholder Management','expert',true),
  ('employee031@company.com','TypeScript','intermediate',true),
  ('employee032@company.com','C#','expert',true),
  ('employee032@company.com','Communication','intermediate',true),
  ('employee032@company.com','Linux','expert',true),
  ('employee032@company.com','Machine Learning','expert',false),
  ('employee032@company.com','Node.js','advanced',true),
  ('employee032@company.com','Product Strategy','advanced',true),
  ('employee032@company.com','REST APIs','beginner',true),
  ('employee032@company.com','Teamwork','expert',false),
  ('employee032@company.com','TypeScript','advanced',false),
  ('employee033@company.com','Angular','expert',false),
  ('employee033@company.com','Azure','intermediate',false),
  ('employee033@company.com','C#','beginner',true),
  ('employee033@company.com','Docker','intermediate',true),
  ('employee033@company.com','Git','advanced',true),
  ('employee033@company.com','Negotiation','expert',true),
  ('employee033@company.com','Project Management','beginner',true),
  ('employee033@company.com','REST APIs','expert',true),
  ('employee033@company.com','Testing Automation','intermediate',true),
  ('employee034@company.com','Agile Methodology','advanced',true),
  ('employee034@company.com','CI CD','beginner',true),
  ('employee034@company.com','Data Analysis','expert',true),
  ('employee034@company.com','Kubernetes','advanced',false),
  ('employee034@company.com','REST APIs','expert',false),
  ('employee034@company.com','Testing Automation','beginner',true),
  ('employee034@company.com','Vue','intermediate',false),
  ('employee035@company.com','Communication','advanced',true),
  ('employee035@company.com','Django','beginner',true),
  ('employee035@company.com','Go','advanced',false),
  ('employee035@company.com','Linux','expert',true),
  ('employee035@company.com','Power BI','advanced',true),
  ('employee035@company.com','Project Management','advanced',false),
  ('employee035@company.com','System Design','expert',true),
  ('employee035@company.com','UI UX Design','beginner',true),
  ('employee036@company.com','Angular','beginner',true),
  ('employee036@company.com','AWS','advanced',false),
  ('employee036@company.com','Azure','advanced',true),
  ('employee036@company.com','Go','advanced',true),
  ('employee036@company.com','Python','advanced',false),
  ('employee036@company.com','React','beginner',true),
  ('employee036@company.com','SQL','advanced',true),
  ('employee036@company.com','Teamwork','beginner',false),
  ('employee036@company.com','TypeScript','advanced',true),
  ('employee036@company.com','Vue','beginner',true),
  ('employee037@company.com','Adaptability','advanced',false),
  ('employee037@company.com','Deep Learning','advanced',true),
  ('employee037@company.com','FastAPI','advanced',false),
  ('employee037@company.com','Problem Solving','expert',false),
  ('employee037@company.com','Product Strategy','beginner',true),
  ('employee037@company.com','Prompt Engineering','beginner',true),
  ('employee037@company.com','Python','advanced',true),
  ('employee037@company.com','Terraform','beginner',false),
  ('employee037@company.com','UI UX Design','intermediate',true),
  ('employee038@company.com','Cybersecurity','expert',false),
  ('employee038@company.com','Docker','expert',true),
  ('employee038@company.com','Flask','beginner',true),
  ('employee038@company.com','Kubernetes','advanced',true),
  ('employee038@company.com','Linux','beginner',true),
  ('employee038@company.com','Negotiation','beginner',true),
  ('employee038@company.com','REST APIs','intermediate',true),
  ('employee038@company.com','System Design','intermediate',false),
  ('employee038@company.com','Terraform','expert',true),
  ('employee039@company.com','Adaptability','beginner',true),
  ('employee039@company.com','Data Analysis','expert',false),
  ('employee039@company.com','Deep Learning','intermediate',true),
  ('employee039@company.com','FastAPI','beginner',false),
  ('employee039@company.com','Git','expert',false),
  ('employee039@company.com','JavaScript','expert',true),
  ('employee039@company.com','Linux','beginner',false),
  ('employee039@company.com','Power BI','intermediate',true),
  ('employee039@company.com','Teamwork','beginner',false),
  ('employee039@company.com','Vue','expert',false),
  ('employee040@company.com','AWS','intermediate',true),
  ('employee040@company.com','Azure','advanced',true),
  ('employee040@company.com','Communication','intermediate',true),
  ('employee040@company.com','Cybersecurity','expert',true),
  ('employee040@company.com','Flask','expert',false),
  ('employee040@company.com','Go','advanced',false),
  ('employee040@company.com','Spring Boot','expert',true),
  ('employee040@company.com','Stakeholder Management','intermediate',true),
  ('employee040@company.com','Teamwork','intermediate',true),
  ('employee040@company.com','Time Management','advanced',true),
  ('employee041@company.com','Docker','advanced',true),
  ('employee041@company.com','GCP','beginner',true),
  ('employee041@company.com','GraphQL','expert',true),
  ('employee041@company.com','JavaScript','expert',false),
  ('employee041@company.com','Linux','expert',true),
  ('employee041@company.com','Time Management','expert',true),
  ('employee041@company.com','TypeScript','beginner',false),
  ('employee042@company.com','Azure','intermediate',true),
  ('employee042@company.com','Docker','expert',true),
  ('employee042@company.com','JavaScript','beginner',false),
  ('employee042@company.com','Power BI','intermediate',true),
  ('employee042@company.com','Product Strategy','expert',true),
  ('employee042@company.com','Stakeholder Management','advanced',true),
  ('employee042@company.com','Tableau','expert',true),
  ('employee043@company.com','Agile Methodology','advanced',true),
  ('employee043@company.com','Git','beginner',true),
  ('employee043@company.com','JavaScript','expert',true),
  ('employee043@company.com','Machine Learning','intermediate',true),
  ('employee043@company.com','Negotiation','advanced',true),
  ('employee043@company.com','Prompt Engineering','advanced',false),
  ('employee043@company.com','System Design','expert',false),
  ('employee043@company.com','Tableau','intermediate',true),
  ('employee043@company.com','Time Management','advanced',true),
  ('employee043@company.com','Vue','beginner',true),
  ('employee044@company.com','Agile Methodology','advanced',true),
  ('employee044@company.com','Cybersecurity','beginner',true),
  ('employee044@company.com','Negotiation','beginner',true),
  ('employee044@company.com','Product Strategy','expert',true),
  ('employee044@company.com','SQL','intermediate',false),
  ('employee044@company.com','Terraform','intermediate',true),
  ('employee045@company.com','Flask','advanced',false),
  ('employee045@company.com','GCP','beginner',true),
  ('employee045@company.com','JavaScript','intermediate',true),
  ('employee045@company.com','Linux','intermediate',true),
  ('employee045@company.com','Machine Learning','advanced',true),
  ('employee045@company.com','Prompt Engineering','expert',false),
  ('employee045@company.com','System Design','expert',true),
  ('employee045@company.com','Testing Automation','beginner',true),
  ('employee046@company.com','Agile Methodology','beginner',true),
  ('employee046@company.com','CI CD','advanced',true),
  ('employee046@company.com','Cybersecurity','advanced',true),
  ('employee046@company.com','Data Analysis','beginner',true),
  ('employee046@company.com','Django','expert',true),
  ('employee046@company.com','Flask','beginner',true),
  ('employee046@company.com','GCP','advanced',true),
  ('employee046@company.com','Git','advanced',true),
  ('employee046@company.com','Power BI','expert',true),
  ('employee046@company.com','Prompt Engineering','expert',false),
  ('employee047@company.com','Adaptability','expert',true),
  ('employee047@company.com','Angular','intermediate',false),
  ('employee047@company.com','Git','expert',true),
  ('employee047@company.com','Prompt Engineering','intermediate',true),
  ('employee047@company.com','React','advanced',true),
  ('employee047@company.com','SQL','advanced',true),
  ('employee048@company.com','Communication','expert',true),
  ('employee048@company.com','Negotiation','intermediate',true),
  ('employee048@company.com','Node.js','intermediate',true),
  ('employee048@company.com','Problem Solving','advanced',true),
  ('employee048@company.com','Prompt Engineering','advanced',true),
  ('employee048@company.com','Python','expert',true),
  ('employee048@company.com','Teamwork','intermediate',false),
  ('employee048@company.com','Terraform','beginner',true),
  ('employee049@company.com','Agile Methodology','beginner',false),
  ('employee049@company.com','C#','intermediate',false),
  ('employee049@company.com','Communication','intermediate',true),
  ('employee049@company.com','Data Analysis','intermediate',false),
  ('employee049@company.com','Power BI','intermediate',true),
  ('employee049@company.com','SQL','expert',true),
  ('employee049@company.com','Vue','expert',true),
  ('employee050@company.com','FastAPI','expert',false),
  ('employee050@company.com','GraphQL','beginner',true),
  ('employee050@company.com','Java','advanced',true),
  ('employee050@company.com','JavaScript','intermediate',true),
  ('employee050@company.com','Linux','intermediate',false),
  ('employee050@company.com','Spring Boot','beginner',true),
  ('employee050@company.com','System Design','intermediate',false),
  ('employee050@company.com','Teamwork','advanced',false),
  ('employee051@company.com','Communication','expert',true),
  ('employee051@company.com','GraphQL','expert',true),
  ('employee051@company.com','Python','expert',true),
  ('employee051@company.com','Spring Boot','advanced',true),
  ('employee051@company.com','Teamwork','expert',true),
  ('employee051@company.com','Terraform','intermediate',true),
  ('employee052@company.com','Angular','expert',false),
  ('employee052@company.com','Communication','expert',true),
  ('employee052@company.com','GraphQL','intermediate',true),
  ('employee052@company.com','JavaScript','beginner',true),
  ('employee052@company.com','Problem Solving','advanced',true),
  ('employee052@company.com','Product Strategy','advanced',true),
  ('employee052@company.com','React','expert',false),
  ('employee052@company.com','REST APIs','advanced',true),
  ('employee052@company.com','Tableau','intermediate',false),
  ('employee052@company.com','Time Management','advanced',true),
  ('employee053@company.com','Deep Learning','expert',true),
  ('employee053@company.com','Docker','expert',true),
  ('employee053@company.com','GCP','advanced',true),
  ('employee053@company.com','Kubernetes','expert',true),
  ('employee053@company.com','Node.js','beginner',true),
  ('employee053@company.com','Power BI','beginner',true),
  ('employee053@company.com','Problem Solving','beginner',true),
  ('employee053@company.com','REST APIs','beginner',true),
  ('employee053@company.com','Stakeholder Management','beginner',true),
  ('employee053@company.com','Time Management','intermediate',false),
  ('employee054@company.com','AWS','advanced',true),
  ('employee054@company.com','GCP','expert',true),
  ('employee054@company.com','Java','expert',false),
  ('employee054@company.com','JavaScript','beginner',false),
  ('employee054@company.com','Power BI','expert',true),
  ('employee054@company.com','Product Strategy','intermediate',false),
  ('employee054@company.com','Python','expert',false),
  ('employee054@company.com','REST APIs','beginner',true),
  ('employee054@company.com','Testing Automation','expert',true),
  ('employee054@company.com','UI UX Design','expert',true),
  ('employee055@company.com','Azure','intermediate',false),
  ('employee055@company.com','Communication','intermediate',false),
  ('employee055@company.com','Docker','intermediate',false),
  ('employee055@company.com','FastAPI','intermediate',false),
  ('employee055@company.com','GCP','beginner',true),
  ('employee055@company.com','SQL','expert',true),
  ('employee055@company.com','Tableau','advanced',true),
  ('employee055@company.com','TypeScript','expert',true),
  ('employee056@company.com','Go','advanced',false),
  ('employee056@company.com','Machine Learning','beginner',false),
  ('employee056@company.com','Project Management','beginner',true),
  ('employee056@company.com','Tableau','expert',true),
  ('employee056@company.com','UI UX Design','advanced',true),
  ('employee056@company.com','Vue','expert',false),
  ('employee057@company.com','AWS','beginner',false),
  ('employee057@company.com','Communication','intermediate',true),
  ('employee057@company.com','JavaScript','advanced',true),
  ('employee057@company.com','Prompt Engineering','beginner',true),
  ('employee057@company.com','SQL','beginner',true),
  ('employee057@company.com','Time Management','intermediate',true),
  ('employee057@company.com','TypeScript','intermediate',true),
  ('employee057@company.com','Vue','advanced',false),
  ('employee058@company.com','C#','advanced',true),
  ('employee058@company.com','Deep Learning','expert',true),
  ('employee058@company.com','Flask','intermediate',true),
  ('employee058@company.com','Go','beginner',true),
  ('employee058@company.com','GraphQL','intermediate',true),
  ('employee058@company.com','Kubernetes','intermediate',false),
  ('employee058@company.com','Product Strategy','beginner',false),
  ('employee058@company.com','TypeScript','advanced',false),
  ('employee058@company.com','Vue','intermediate',false),
  ('employee059@company.com','Django','expert',true),
  ('employee059@company.com','Excel','beginner',true),
  ('employee059@company.com','Git','expert',false),
  ('employee059@company.com','Node.js','beginner',true),
  ('employee059@company.com','Teamwork','expert',false),
  ('employee059@company.com','Testing Automation','intermediate',false),
  ('employee059@company.com','UI UX Design','advanced',true),
  ('employee059@company.com','Vue','beginner',true),
  ('employee060@company.com','AWS','expert',true),
  ('employee060@company.com','Communication','advanced',true),
  ('employee060@company.com','Cybersecurity','advanced',true),
  ('employee060@company.com','Deep Learning','expert',true),
  ('employee060@company.com','Java','intermediate',false),
  ('employee060@company.com','Project Management','beginner',true),
  ('employee060@company.com','React','expert',true),
  ('employee060@company.com','Tableau','beginner',true),
  ('employee061@company.com','Cybersecurity','expert',false),
  ('employee061@company.com','Data Analysis','expert',false),
  ('employee061@company.com','GCP','advanced',true),
  ('employee061@company.com','Git','advanced',true),
  ('employee061@company.com','JavaScript','beginner',true),
  ('employee061@company.com','Node.js','beginner',true),
  ('employee061@company.com','Spring Boot','intermediate',true),
  ('employee061@company.com','Teamwork','intermediate',true),
  ('employee062@company.com','AWS','expert',true),
  ('employee062@company.com','Cybersecurity','expert',true),
  ('employee062@company.com','Docker','expert',true),
  ('employee062@company.com','Power BI','beginner',false),
  ('employee062@company.com','REST APIs','beginner',true),
  ('employee062@company.com','Teamwork','beginner',true),
  ('employee062@company.com','UI UX Design','advanced',true),
  ('employee062@company.com','Vue','advanced',true),
  ('employee063@company.com','Agile Methodology','expert',true),
  ('employee063@company.com','CI CD','beginner',false),
  ('employee063@company.com','Data Analysis','beginner',true),
  ('employee063@company.com','Django','beginner',true),
  ('employee063@company.com','Git','advanced',true),
  ('employee063@company.com','JavaScript','advanced',true),
  ('employee063@company.com','Terraform','intermediate',true),
  ('employee064@company.com','Adaptability','advanced',false),
  ('employee064@company.com','Azure','beginner',true),
  ('employee064@company.com','C#','intermediate',true),
  ('employee064@company.com','Cybersecurity','beginner',true),
  ('employee064@company.com','GCP','intermediate',false),
  ('employee064@company.com','Go','intermediate',true),
  ('employee064@company.com','Testing Automation','expert',true),
  ('employee065@company.com','Azure','beginner',true),
  ('employee065@company.com','Django','expert',true),
  ('employee065@company.com','JavaScript','beginner',true),
  ('employee065@company.com','Machine Learning','expert',false),
  ('employee065@company.com','Power BI','expert',true),
  ('employee065@company.com','Product Strategy','advanced',false),
  ('employee065@company.com','Python','beginner',true),
  ('employee065@company.com','System Design','intermediate',false),
  ('employee065@company.com','Teamwork','advanced',true),
  ('employee065@company.com','UI UX Design','beginner',true),
  ('employee066@company.com','Power BI','advanced',true),
  ('employee066@company.com','Product Strategy','intermediate',false),
  ('employee066@company.com','Python','expert',true),
  ('employee066@company.com','Spring Boot','beginner',true),
  ('employee066@company.com','System Design','intermediate',true),
  ('employee066@company.com','Tableau','intermediate',true),
  ('employee066@company.com','Teamwork','expert',true),
  ('employee066@company.com','TypeScript','beginner',true),
  ('employee066@company.com','Vue','beginner',false),
  ('employee067@company.com','Leadership','beginner',false),
  ('employee067@company.com','Machine Learning','expert',false),
  ('employee067@company.com','Python','expert',true),
  ('employee067@company.com','Teamwork','expert',true),
  ('employee067@company.com','Terraform','advanced',true),
  ('employee067@company.com','UI UX Design','expert',false),
  ('employee067@company.com','Vue','advanced',false),
  ('employee068@company.com','Azure','intermediate',true),
  ('employee068@company.com','CI CD','expert',false),
  ('employee068@company.com','Communication','advanced',false),
  ('employee068@company.com','Kubernetes','advanced',true),
  ('employee068@company.com','Power BI','advanced',false),
  ('employee068@company.com','Problem Solving','intermediate',true),
  ('employee068@company.com','Project Management','advanced',true),
  ('employee068@company.com','Python','expert',true),
  ('employee068@company.com','Stakeholder Management','advanced',false),
  ('employee069@company.com','FastAPI','intermediate',true),
  ('employee069@company.com','Go','beginner',false),
  ('employee069@company.com','Negotiation','beginner',true),
  ('employee069@company.com','Power BI','intermediate',true),
  ('employee069@company.com','Product Strategy','intermediate',true),
  ('employee069@company.com','Time Management','beginner',true),
  ('employee070@company.com','Data Analysis','beginner',false),
  ('employee070@company.com','Go','expert',true),
  ('employee070@company.com','GraphQL','intermediate',true),
  ('employee070@company.com','Problem Solving','intermediate',true),
  ('employee070@company.com','Project Management','advanced',true),
  ('employee070@company.com','React','intermediate',false),
  ('employee070@company.com','SQL','expert',false),
  ('employee070@company.com','System Design','expert',true),
  ('employee070@company.com','TypeScript','intermediate',false),
  ('employee070@company.com','UI UX Design','advanced',true),
  ('employee071@company.com','Azure','advanced',false),
  ('employee071@company.com','Communication','advanced',false),
  ('employee071@company.com','Cybersecurity','advanced',true),
  ('employee071@company.com','Data Analysis','advanced',true),
  ('employee071@company.com','FastAPI','expert',true),
  ('employee071@company.com','GraphQL','beginner',true),
  ('employee071@company.com','JavaScript','advanced',true),
  ('employee071@company.com','Leadership','advanced',true),
  ('employee071@company.com','Time Management','beginner',true),
  ('employee071@company.com','TypeScript','advanced',true),
  ('employee072@company.com','Data Analysis','beginner',false),
  ('employee072@company.com','Docker','beginner',true),
  ('employee072@company.com','JavaScript','beginner',true),
  ('employee072@company.com','Teamwork','advanced',true),
  ('employee072@company.com','Testing Automation','intermediate',true),
  ('employee072@company.com','Time Management','intermediate',true),
  ('employee073@company.com','Communication','beginner',true),
  ('employee073@company.com','GCP','beginner',true),
  ('employee073@company.com','Kubernetes','intermediate',true),
  ('employee073@company.com','Project Management','intermediate',true),
  ('employee073@company.com','REST APIs','beginner',true),
  ('employee073@company.com','Teamwork','intermediate',true),
  ('employee073@company.com','Time Management','advanced',true),
  ('employee074@company.com','Data Analysis','beginner',false),
  ('employee074@company.com','Node.js','beginner',true),
  ('employee074@company.com','Project Management','advanced',true),
  ('employee074@company.com','Stakeholder Management','beginner',true),
  ('employee074@company.com','Time Management','expert',true),
  ('employee074@company.com','UI UX Design','beginner',false),
  ('employee075@company.com','Adaptability','beginner',true),
  ('employee075@company.com','Docker','beginner',false),
  ('employee075@company.com','Node.js','beginner',false),
  ('employee075@company.com','Problem Solving','advanced',true),
  ('employee075@company.com','Terraform','intermediate',false),
  ('employee075@company.com','TypeScript','advanced',true),
  ('employee076@company.com','Azure','advanced',false),
  ('employee076@company.com','Docker','intermediate',true),
  ('employee076@company.com','GraphQL','expert',true),
  ('employee076@company.com','Leadership','expert',true),
  ('employee076@company.com','Linux','advanced',false),
  ('employee076@company.com','Power BI','expert',true),
  ('employee076@company.com','Product Strategy','advanced',true),
  ('employee076@company.com','Python','intermediate',true),
  ('employee076@company.com','SQL','expert',true),
  ('employee077@company.com','Angular','beginner',false),
  ('employee077@company.com','Communication','beginner',true),
  ('employee077@company.com','Excel','advanced',false),
  ('employee077@company.com','Negotiation','advanced',true),
  ('employee077@company.com','Stakeholder Management','advanced',true),
  ('employee077@company.com','Terraform','intermediate',true),
  ('employee077@company.com','Testing Automation','intermediate',true),
  ('employee077@company.com','Time Management','expert',true),
  ('employee077@company.com','TypeScript','beginner',true),
  ('employee078@company.com','Angular','advanced',true),
  ('employee078@company.com','AWS','expert',true),
  ('employee078@company.com','Communication','advanced',true),
  ('employee078@company.com','Data Analysis','advanced',false),
  ('employee078@company.com','GraphQL','advanced',true),
  ('employee078@company.com','JavaScript','advanced',false),
  ('employee078@company.com','Product Strategy','beginner',false),
  ('employee078@company.com','Vue','expert',true),
  ('employee079@company.com','AWS','advanced',true),
  ('employee079@company.com','Data Analysis','beginner',false),
  ('employee079@company.com','Django','expert',true),
  ('employee079@company.com','Docker','intermediate',true),
  ('employee079@company.com','FastAPI','beginner',false),
  ('employee079@company.com','Go','advanced',true),
  ('employee079@company.com','GraphQL','intermediate',true),
  ('employee079@company.com','Kubernetes','intermediate',false),
  ('employee079@company.com','Product Strategy','intermediate',false),
  ('employee080@company.com','AWS','expert',true),
  ('employee080@company.com','Excel','expert',true),
  ('employee080@company.com','Flask','intermediate',false),
  ('employee080@company.com','GCP','intermediate',false),
  ('employee080@company.com','Git','expert',true),
  ('employee080@company.com','Go','advanced',false),
  ('employee080@company.com','GraphQL','beginner',true),
  ('employee080@company.com','Kubernetes','beginner',true),
  ('employee080@company.com','Machine Learning','advanced',false),
  ('employee080@company.com','TypeScript','beginner',true),
  ('employee081@company.com','Adaptability','beginner',true),
  ('employee081@company.com','Agile Methodology','intermediate',false),
  ('employee081@company.com','Communication','advanced',true),
  ('employee081@company.com','Django','expert',true),
  ('employee081@company.com','GraphQL','beginner',false),
  ('employee081@company.com','JavaScript','expert',true),
  ('employee081@company.com','Problem Solving','expert',false),
  ('employee081@company.com','Product Strategy','advanced',true),
  ('employee081@company.com','Testing Automation','advanced',true),
  ('employee082@company.com','CI CD','advanced',true),
  ('employee082@company.com','Excel','intermediate',true),
  ('employee082@company.com','JavaScript','beginner',false),
  ('employee082@company.com','Leadership','beginner',true),
  ('employee082@company.com','Negotiation','intermediate',true),
  ('employee082@company.com','Node.js','beginner',true),
  ('employee082@company.com','Problem Solving','beginner',false),
  ('employee082@company.com','Prompt Engineering','intermediate',true),
  ('employee082@company.com','Spring Boot','expert',false),
  ('employee082@company.com','Teamwork','advanced',false),
  ('employee083@company.com','Docker','expert',true),
  ('employee083@company.com','Git','intermediate',false),
  ('employee083@company.com','Go','beginner',false),
  ('employee083@company.com','Java','beginner',true),
  ('employee083@company.com','JavaScript','intermediate',true),
  ('employee083@company.com','Kubernetes','expert',true),
  ('employee083@company.com','Power BI','advanced',false),
  ('employee083@company.com','SQL','beginner',true),
  ('employee083@company.com','Testing Automation','beginner',true),
  ('employee084@company.com','Communication','advanced',true),
  ('employee084@company.com','GraphQL','advanced',true),
  ('employee084@company.com','Java','intermediate',false),
  ('employee084@company.com','Leadership','expert',true),
  ('employee084@company.com','Problem Solving','expert',false),
  ('employee084@company.com','SQL','intermediate',true),
  ('employee084@company.com','System Design','beginner',true),
  ('employee084@company.com','UI UX Design','intermediate',true),
  ('employee085@company.com','CI CD','expert',false),
  ('employee085@company.com','Excel','intermediate',false),
  ('employee085@company.com','Flask','intermediate',false),
  ('employee085@company.com','Java','expert',true),
  ('employee085@company.com','REST APIs','advanced',false),
  ('employee085@company.com','Vue','intermediate',false),
  ('employee086@company.com','Kubernetes','advanced',false),
  ('employee086@company.com','Linux','beginner',true),
  ('employee086@company.com','Machine Learning','advanced',false),
  ('employee086@company.com','Negotiation','expert',true),
  ('employee086@company.com','Product Strategy','beginner',true),
  ('employee086@company.com','Prompt Engineering','advanced',false),
  ('employee086@company.com','SQL','advanced',true),
  ('employee086@company.com','Time Management','beginner',true),
  ('employee087@company.com','Agile Methodology','intermediate',true),
  ('employee087@company.com','Azure','intermediate',true),
  ('employee087@company.com','Flask','intermediate',true),
  ('employee087@company.com','Go','intermediate',true),
  ('employee087@company.com','Linux','advanced',true),
  ('employee087@company.com','Negotiation','beginner',true),
  ('employee087@company.com','Project Management','intermediate',true),
  ('employee087@company.com','Testing Automation','advanced',false),
  ('employee087@company.com','TypeScript','advanced',true),
  ('employee087@company.com','Vue','advanced',false),
  ('employee088@company.com','Excel','advanced',true),
  ('employee088@company.com','FastAPI','intermediate',false),
  ('employee088@company.com','Java','beginner',true),
  ('employee088@company.com','Negotiation','advanced',true),
  ('employee088@company.com','React','intermediate',true),
  ('employee088@company.com','Spring Boot','advanced',true),
  ('employee088@company.com','SQL','advanced',true),
  ('employee088@company.com','Stakeholder Management','intermediate',false),
  ('employee088@company.com','Tableau','beginner',true),
  ('employee088@company.com','Vue','advanced',true),
  ('employee089@company.com','Cybersecurity','intermediate',true),
  ('employee089@company.com','Deep Learning','advanced',true),
  ('employee089@company.com','Docker','expert',true),
  ('employee089@company.com','FastAPI','expert',false),
  ('employee089@company.com','Go','intermediate',false),
  ('employee089@company.com','Leadership','beginner',true),
  ('employee089@company.com','Spring Boot','intermediate',true),
  ('employee090@company.com','Agile Methodology','advanced',true),
  ('employee090@company.com','C#','expert',true),
  ('employee090@company.com','Data Analysis','expert',false),
  ('employee090@company.com','Django','expert',true),
  ('employee090@company.com','GCP','advanced',true),
  ('employee090@company.com','Go','advanced',true),
  ('employee090@company.com','Leadership','advanced',false),
  ('employee090@company.com','Product Strategy','expert',true),
  ('employee090@company.com','Python','expert',true),
  ('employee090@company.com','UI UX Design','advanced',true),
  ('employee091@company.com','Agile Methodology','intermediate',true),
  ('employee091@company.com','Cybersecurity','advanced',true),
  ('employee091@company.com','FastAPI','expert',true),
  ('employee091@company.com','Go','intermediate',true),
  ('employee091@company.com','Leadership','expert',false),
  ('employee091@company.com','Negotiation','advanced',true),
  ('employee091@company.com','Python','advanced',true),
  ('employee091@company.com','TypeScript','expert',true),
  ('employee092@company.com','AWS','intermediate',true),
  ('employee092@company.com','Docker','intermediate',true),
  ('employee092@company.com','Linux','beginner',true),
  ('employee092@company.com','Machine Learning','intermediate',true),
  ('employee092@company.com','Product Strategy','expert',false),
  ('employee092@company.com','Stakeholder Management','advanced',true),
  ('employee093@company.com','Adaptability','advanced',false),
  ('employee093@company.com','Angular','intermediate',true),
  ('employee093@company.com','C#','advanced',false),
  ('employee093@company.com','Docker','intermediate',true),
  ('employee093@company.com','Flask','beginner',true),
  ('employee093@company.com','REST APIs','advanced',true),
  ('employee093@company.com','Spring Boot','intermediate',true),
  ('employee093@company.com','SQL','intermediate',true),
  ('employee093@company.com','System Design','beginner',true),
  ('employee093@company.com','Tableau','intermediate',true),
  ('employee094@company.com','Adaptability','beginner',true),
  ('employee094@company.com','Agile Methodology','beginner',true),
  ('employee094@company.com','Problem Solving','expert',false),
  ('employee094@company.com','Product Strategy','intermediate',true),
  ('employee094@company.com','Prompt Engineering','beginner',true),
  ('employee094@company.com','REST APIs','advanced',true),
  ('employee094@company.com','Teamwork','advanced',true),
  ('employee095@company.com','CI CD','expert',false),
  ('employee095@company.com','Cybersecurity','intermediate',true),
  ('employee095@company.com','Django','advanced',true),
  ('employee095@company.com','GCP','intermediate',false),
  ('employee095@company.com','Leadership','beginner',true),
  ('employee095@company.com','Product Strategy','intermediate',true),
  ('employee095@company.com','Project Management','advanced',true),
  ('employee095@company.com','Python','advanced',false),
  ('employee095@company.com','Tableau','advanced',false),
  ('employee095@company.com','Time Management','advanced',true),
  ('employee096@company.com','Data Analysis','advanced',true),
  ('employee096@company.com','Power BI','beginner',false),
  ('employee096@company.com','React','expert',true),
  ('employee096@company.com','Spring Boot','intermediate',true),
  ('employee096@company.com','Testing Automation','beginner',true),
  ('employee096@company.com','UI UX Design','intermediate',true),
  ('employee096@company.com','Vue','expert',true),
  ('employee097@company.com','Agile Methodology','expert',true),
  ('employee097@company.com','Leadership','expert',true),
  ('employee097@company.com','Product Strategy','beginner',true),
  ('employee097@company.com','Project Management','advanced',true),
  ('employee097@company.com','Teamwork','expert',true),
  ('employee097@company.com','Time Management','beginner',true),
  ('employee098@company.com','Go','advanced',true),
  ('employee098@company.com','GraphQL','beginner',false),
  ('employee098@company.com','Kubernetes','beginner',false),
  ('employee098@company.com','Linux','advanced',true),
  ('employee098@company.com','Power BI','intermediate',true),
  ('employee098@company.com','REST APIs','advanced',true),
  ('employee098@company.com','System Design','beginner',true),
  ('employee099@company.com','CI CD','expert',true),
  ('employee099@company.com','Communication','beginner',true),
  ('employee099@company.com','Excel','intermediate',true),
  ('employee099@company.com','FastAPI','expert',false),
  ('employee099@company.com','Git','beginner',true),
  ('employee099@company.com','JavaScript','expert',true),
  ('employee099@company.com','Project Management','expert',true),
  ('employee099@company.com','Prompt Engineering','advanced',true),
  ('employee099@company.com','Python','beginner',false),
  ('employee099@company.com','Vue','advanced',true),
  ('employee100@company.com','Adaptability','intermediate',true),
  ('employee100@company.com','C#','advanced',true),
  ('employee100@company.com','Communication','intermediate',true),
  ('employee100@company.com','Data Analysis','intermediate',true),
  ('employee100@company.com','Leadership','expert',true),
  ('employee100@company.com','Problem Solving','intermediate',true),
  ('employee100@company.com','Spring Boot','intermediate',true),
  ('employee100@company.com','Stakeholder Management','advanced',true),
  ('employee100@company.com','UI UX Design','expert',true);

insert into public.employee_skills (employee_id, skill_id, proficiency, self_rated)
select p.id, s.id, ses.proficiency, ses.self_rated
from staging_employee_skills ses
join public.profiles p on lower(p.email) = lower(ses.employee_email)
join public.skills s on lower(s.name) = lower(ses.skill_name)
on conflict (employee_id, skill_id) do update set
  proficiency = excluded.proficiency,
  self_rated = excluded.self_rated,
  updated_at = now();

create temporary table staging_availability (employee_email text, status availability_status, available_from date, notes text) on commit drop;
insert into staging_availability (employee_email, status, available_from, notes) values
  ('employee001@company.com','in_project','2026-05-23','Allocated to active project'),
  ('employee002@company.com','available','2026-06-23','Available for staffing'),
  ('employee003@company.com','in_project','2026-05-23','Allocated to active project'),
  ('employee004@company.com','available','2026-04-24','Available for staffing'),
  ('employee005@company.com','available','2026-04-27','Available for staffing'),
  ('employee006@company.com','in_project','2026-05-11','Allocated to active project'),
  ('employee007@company.com','available','2026-04-26','Available for staffing'),
  ('employee008@company.com','available','2026-05-06','Available for staffing'),
  ('employee009@company.com','available','2026-04-07','Available for staffing'),
  ('employee010@company.com','on_leave','2026-06-15','Planned leave'),
  ('employee011@company.com','in_project','2026-06-22','Allocated to active project'),
  ('employee012@company.com','in_project','2026-04-09','Allocated to active project'),
  ('employee013@company.com','available','2026-06-18','Available for staffing'),
  ('employee014@company.com','in_project','2026-06-27','Allocated to active project'),
  ('employee015@company.com','available','2026-06-01','Available for staffing'),
  ('employee016@company.com','in_project','2026-07-04','Allocated to active project'),
  ('employee017@company.com','in_project','2026-04-10','Allocated to active project'),
  ('employee018@company.com','available','2026-05-04','Available for staffing'),
  ('employee019@company.com','in_project','2026-07-04','Allocated to active project'),
  ('employee020@company.com','available','2026-06-21','Available for staffing'),
  ('employee021@company.com','available','2026-04-09','Available for staffing'),
  ('employee022@company.com','available','2026-05-12','Available for staffing'),
  ('employee023@company.com','available','2026-04-15','Available for staffing'),
  ('employee024@company.com','unavailable','2026-06-27','Limited bandwidth this month'),
  ('employee025@company.com','available','2026-05-03','Available for staffing'),
  ('employee026@company.com','available','2026-04-27','Available for staffing'),
  ('employee027@company.com','available','2026-04-21','Available for staffing'),
  ('employee028@company.com','available','2026-04-25','Available for staffing'),
  ('employee029@company.com','available','2026-05-30','Available for staffing'),
  ('employee030@company.com','available','2026-07-04','Available for staffing'),
  ('employee031@company.com','available','2026-05-06','Available for staffing'),
  ('employee032@company.com','in_project','2026-04-25','Allocated to active project'),
  ('employee033@company.com','in_project','2026-05-14','Allocated to active project'),
  ('employee034@company.com','in_project','2026-06-16','Allocated to active project'),
  ('employee035@company.com','in_project','2026-05-29','Allocated to active project'),
  ('employee036@company.com','available','2026-06-14','Available for staffing'),
  ('employee037@company.com','available','2026-07-02','Available for staffing'),
  ('employee038@company.com','available','2026-06-27','Available for staffing'),
  ('employee039@company.com','available','2026-06-08','Available for staffing'),
  ('employee040@company.com','in_project','2026-05-12','Allocated to active project'),
  ('employee041@company.com','on_leave','2026-06-30','Planned leave'),
  ('employee042@company.com','in_project','2026-05-26','Allocated to active project'),
  ('employee043@company.com','available','2026-04-28','Available for staffing'),
  ('employee044@company.com','in_project','2026-04-26','Allocated to active project'),
  ('employee045@company.com','available','2026-05-16','Available for staffing'),
  ('employee046@company.com','in_project','2026-04-25','Allocated to active project'),
  ('employee047@company.com','on_leave','2026-05-31','Planned leave'),
  ('employee048@company.com','available','2026-05-04','Available for staffing'),
  ('employee049@company.com','in_project','2026-04-27','Allocated to active project'),
  ('employee050@company.com','unavailable','2026-05-20','Limited bandwidth this month'),
  ('employee051@company.com','available','2026-07-01','Available for staffing'),
  ('employee052@company.com','available','2026-05-12','Available for staffing'),
  ('employee053@company.com','available','2026-07-02','Available for staffing'),
  ('employee054@company.com','unavailable','2026-05-27','Limited bandwidth this month'),
  ('employee055@company.com','available','2026-06-01','Available for staffing'),
  ('employee056@company.com','available','2026-05-31','Available for staffing'),
  ('employee057@company.com','on_leave','2026-04-23','Planned leave'),
  ('employee058@company.com','in_project','2026-06-04','Allocated to active project'),
  ('employee059@company.com','in_project','2026-04-15','Allocated to active project'),
  ('employee060@company.com','available','2026-04-11','Available for staffing'),
  ('employee061@company.com','available','2026-04-07','Available for staffing'),
  ('employee062@company.com','available','2026-06-17','Available for staffing'),
  ('employee063@company.com','available','2026-05-12','Available for staffing'),
  ('employee064@company.com','available','2026-04-22','Available for staffing'),
  ('employee065@company.com','in_project','2026-05-11','Allocated to active project'),
  ('employee066@company.com','on_leave','2026-07-04','Planned leave'),
  ('employee067@company.com','available','2026-05-22','Available for staffing'),
  ('employee068@company.com','in_project','2026-05-14','Allocated to active project'),
  ('employee069@company.com','available','2026-05-30','Available for staffing'),
  ('employee070@company.com','available','2026-04-14','Available for staffing'),
  ('employee071@company.com','in_project','2026-05-29','Allocated to active project'),
  ('employee072@company.com','available','2026-04-07','Available for staffing'),
  ('employee073@company.com','available','2026-04-27','Available for staffing'),
  ('employee074@company.com','in_project','2026-06-17','Allocated to active project'),
  ('employee075@company.com','available','2026-06-23','Available for staffing'),
  ('employee076@company.com','on_leave','2026-05-21','Planned leave'),
  ('employee077@company.com','in_project','2026-06-23','Allocated to active project'),
  ('employee078@company.com','available','2026-07-03','Available for staffing'),
  ('employee079@company.com','in_project','2026-04-14','Allocated to active project'),
  ('employee080@company.com','unavailable','2026-05-24','Limited bandwidth this month'),
  ('employee081@company.com','available','2026-05-13','Available for staffing'),
  ('employee082@company.com','in_project','2026-05-11','Allocated to active project'),
  ('employee083@company.com','available','2026-05-12','Available for staffing'),
  ('employee084@company.com','available','2026-06-05','Available for staffing'),
  ('employee085@company.com','in_project','2026-06-07','Allocated to active project'),
  ('employee086@company.com','in_project','2026-06-27','Allocated to active project'),
  ('employee087@company.com','available','2026-06-22','Available for staffing'),
  ('employee088@company.com','on_leave','2026-05-11','Planned leave'),
  ('employee089@company.com','available','2026-06-25','Available for staffing'),
  ('employee090@company.com','in_project','2026-06-02','Allocated to active project'),
  ('employee091@company.com','in_project','2026-05-07','Allocated to active project'),
  ('employee092@company.com','unavailable','2026-04-08','Limited bandwidth this month'),
  ('employee093@company.com','available','2026-06-03','Available for staffing'),
  ('employee094@company.com','available','2026-04-24','Available for staffing'),
  ('employee095@company.com','available','2026-06-13','Available for staffing'),
  ('employee096@company.com','available','2026-04-14','Available for staffing'),
  ('employee097@company.com','in_project','2026-04-17','Allocated to active project'),
  ('employee098@company.com','available','2026-06-23','Available for staffing'),
  ('employee099@company.com','on_leave','2026-04-26','Planned leave'),
  ('employee100@company.com','available','2026-07-02','Available for staffing');

insert into public.employee_availability (employee_id, status, available_from, notes)
select p.id, sa.status, sa.available_from, sa.notes
from staging_availability sa
join public.profiles p on lower(p.email) = lower(sa.employee_email)
on conflict (employee_id) do update set
  status = excluded.status,
  available_from = excluded.available_from,
  notes = excluded.notes,
  updated_at = now();


-- Ensure job_requirements has expected columns for import.
alter table if exists public.job_requirements add column if not exists required_skills text[];
alter table if exists public.job_requirements add column if not exists preferred_skills text[];
alter table if exists public.job_requirements add column if not exists is_active boolean default true;

create table if not exists public.job_requirement_skills (
  id uuid primary key default gen_random_uuid(),
  job_requirement_id uuid not null references public.job_requirements(id) on delete cascade,
  skill_id uuid not null references public.skills(id) on delete cascade,
  importance text check (importance in ('required','preferred')) default 'required',
  unique(job_requirement_id, skill_id)
);
create temporary table staging_jobs (title text, department text, min_experience_years int, required_skills text, preferred_skills text) on commit drop;
insert into staging_jobs (title, department, min_experience_years, required_skills, preferred_skills) values
  ('Software Engineer','Engineering',2,'Python,SQL,Problem Solving,REST APIs','AWS,React,Git'),
  ('Senior Software Engineer','Engineering',5,'System Design,JavaScript,TypeScript,CI CD','AWS,Docker,Kubernetes'),
  ('Data Analyst','Data',2,'SQL,Data Analysis,Excel,Tableau','Power BI,Python,Communication'),
  ('Data Scientist','Data',4,'Python,Machine Learning,Deep Learning,SQL','AWS,Prompt Engineering,Tableau'),
  ('ML Engineer','Data',4,'Python,Machine Learning,Docker,Kubernetes','GCP,FastAPI,System Design'),
  ('Backend Developer','IT',3,'Java,Node.js,REST APIs,SQL','Docker,AWS,Testing Automation'),
  ('Frontend Developer','IT',3,'React,TypeScript,JavaScript,UI UX Design','GraphQL,Testing Automation,Communication'),
  ('Full Stack Developer','IT',4,'React,Node.js,SQL,Docker','AWS,TypeScript,CI CD'),
  ('Cloud Engineer','Engineering',4,'AWS,Terraform,Docker,Kubernetes','Azure,GCP,Linux'),
  ('DevOps Engineer','Engineering',4,'CI CD,Docker,Kubernetes,Linux','Terraform,AWS,Git'),
  ('QA Engineer','Engineering',3,'Testing Automation,JavaScript,REST APIs,Problem Solving','CI CD,Communication,SQL'),
  ('Security Analyst','Security',3,'Cybersecurity,Linux,Problem Solving,Communication','AWS,Python,Stakeholder Management'),
  ('Product Manager','Product',5,'Product Strategy,Project Management,Stakeholder Management,Communication','Data Analysis,Agile Methodology,Leadership'),
  ('HR Manager','HR',5,'Leadership,Communication,Negotiation,Project Management','Stakeholder Management,Time Management,Adaptability'),
  ('UI UX Designer','Design',2,'UI UX Design,Communication,Problem Solving,Adaptability','Product Strategy,Stakeholder Management,Teamwork');

insert into public.job_requirements (title, department, min_experience_years, required_skills, preferred_skills, is_active)
select
  sj.title,
  sj.department,
  sj.min_experience_years,
  regexp_split_to_array(sj.required_skills, '\s*,\s*'),
  case when coalesce(trim(sj.preferred_skills), '') = '' then null else regexp_split_to_array(sj.preferred_skills, '\s*,\s*') end,
  true
from staging_jobs sj
on conflict do nothing;

-- Populate normalized job_requirement_skills table
insert into public.job_requirement_skills (job_requirement_id, skill_id, importance)
select jr.id, s.id, 'required'
from public.job_requirements jr
cross join lateral unnest(coalesce(jr.required_skills, '{}')) req(skill_name)
join public.skills s on lower(s.name) = lower(req.skill_name)
on conflict (job_requirement_id, skill_id) do update set importance = 'required';

insert into public.job_requirement_skills (job_requirement_id, skill_id, importance)
select jr.id, s.id, 'preferred'
from public.job_requirements jr
cross join lateral unnest(coalesce(jr.preferred_skills, '{}')) pref(skill_name)
join public.skills s on lower(s.name) = lower(pref.skill_name)
on conflict (job_requirement_id, skill_id) do update set importance = 'preferred';

