-- Clear all cached learning path plans that were generated by the static
-- rule-based fallback (buildFallbackPlan). Now that the edge function
-- exclusively uses Gemini for plan generation, these stale rows must be
-- removed so that every subsequent request triggers a fresh AI-generated plan.
DELETE FROM learning_path_plans;
